---
title: "Website"
author: "Tania Lewis"
output: html_document
---

Template for posting analysis to web using GitHub

1) Load escapement data:

```{r}
escapement <- read.csv ("knb.92020.1.csv", stringsAsFactors = FALSE)

```
```{r}
library(tidyr)
library(dplyr)
library(ggplot2)
library(DT)
library(leaflet)
```
Calculate median annual excapement by species, first seperate year out of the date:
```{r}
median_esc <- escapement %>%
  separate(sampleDate, c("Year", "Month", "Day"), sep = "-") %>%
  group_by (Species, Location, Year) %>%
  summarise (escapement = sum(DailyCount))%>%
  group_by(Species) %>%
  summarise(median_escapement = median(escapement))

median_esc
```
```{r}
ggplot(median_esc, aes(Species, median_escapement))+
  geom_col()+
  coord_flip()

```
Create interactive table
```{r}
datatable(median_esc)
```
Using leaflet package to make interactive map
First pull out each distinct location
```{r}
locations<-escapement %>%
  distinct(Location, Latitude, Longitude) %>%
  drop_na()
```
```{r}
leaflet(locations) %>%
  addTiles() %>%
  addMarkers(~ -abs(Longitude), ~ Latitude, popup = ~Location)
```

